"""How the generated module reaches torch.

The access modes, and the ABI table the shim one reads (`torch_abi.toml`).  The
table is generated by `abi_detect` and cross-checked by `cpp_detect`.  Everything
here is pure python and testable without a GPU.  Only `dtype_index_table` consults
triton, and lazily, the same way the rest consults torch.
"""

from __future__ import annotations

import ctypes
import dataclasses
import enum
import functools
import pathlib
import sys
from typing import Any

if sys.version_info >= (3, 11):
    import tomllib
else:  # the same parser, before it joined the stdlib
    import tomli as tomllib  # pyright: ignore[reportMissingImports]

from ..python_intf.cpython_abi import pyobject_size

#: How many dtype codes the C side reserves room for; mirrors INTJ_NDTYPES.
NDTYPES = 64


class TorchAccess(enum.Enum):
    """How a generated module reads a tensor's pointer, dtype and storage size."""

    #: Pick by what the running torch and toolchain support.
    AUTO = "auto"
    #: Call through the interpreter.  Assumes nothing but THPDtype, which self-checks.
    CPYTHON = "cpython"
    #: Read torch's structs at verified offsets.  No torch code runs.
    SHIM = "shim"
    #: Compile the extension as C++ against torch's headers.
    CXX = "cxx"


@dataclasses.dataclass(frozen=True)
class TensorABI:
    """Byte offsets the `SHIM` mode reads, plus the dtype-to-element-size table.

    Both halves come from one entry of `torch_abi.toml`, keyed on the torch
    version: the offsets were measured on a torch with exactly those dtypes, so
    they are verified together or not at all.
    """

    cdata: int  # PyObject*    -> TensorImpl*
    storage: int  # TensorImpl*  -> StorageImpl*
    storage_offset: int  # TensorImpl*  -> int64
    numel: int  # TensorImpl*  -> int64
    data_type: int  # TensorImpl*  -> TypeMeta index, low byte
    s_data: int  # StorageImpl* -> void*
    s_nbytes: int  # StorageImpl* -> int64
    itemsize: bytes  # dtype code -> element size, NDTYPES long

    def as_args(self) -> tuple[Any, ...]:
        """The tuple `set_torch_version` parses."""
        return (
            self.cdata, self.storage, self.storage_offset, self.numel,
            self.data_type, self.s_data, self.s_nbytes, self.itemsize,
        )


def dtype_code(dtype: Any) -> int:
    """The `at::ScalarType` value of a `torch.dtype`, read off the singleton.

    `struct THPDtype { PyObject_HEAD at::ScalarType scalar_type; char name[65]; }`
    has been byte-identical since torch 1.13, and `ScalarType` is an
    `enum class : int8_t`.  The C side makes the same read and validates it
    against the embedded `name[]`; this is its python twin.
    """
    return ctypes.c_int8.from_address(id(dtype) + pyobject_size()).value


@functools.lru_cache(maxsize=1)
def live_dtypes() -> dict[int, tuple[str, int]]:
    """dtype code -> (torch's own spelling, element size), from the running torch.

    `str(dtype)` rather than the attribute name: `torch.half` and `torch.float16`
    are one dtype with one canonical spelling, and only that spelling is stable
    enough to compare a recorded entry against.

    `dtype.itemsize` reads the `TypeMeta` directly, so it answers for dtypes this
    build cannot actually allocate and, unlike a zero-element `torch.empty`,
    warns for none of the experimental ones.
    """
    import torch

    found: dict[int, tuple[str, int]] = {}
    for name in dir(torch):
        value = getattr(torch, name, None)
        if not isinstance(value, torch.dtype):
            continue
        code = dtype_code(value)
        if 0 <= code < NDTYPES:
            found[code] = (str(value).split(".")[-1], value.itemsize)
    return found


def itemsize_bytes(dtypes: dict[int, tuple[str, int]]) -> bytes:
    """The `NDTYPES`-long table the C side indexes by dtype code.

    A zero entry means "no such dtype", which the C side treats as a layout
    mismatch rather than computing a pointer from a guess.
    """
    table = bytearray(NDTYPES)
    for code, (_, size) in dtypes.items():
        table[code] = size
    return bytes(table)


@functools.lru_cache(maxsize=4)
def itemsize_table(version: tuple[int, int] | None = None) -> bytes | None:
    """The recorded dtype -> element size table for `version`, or None.

    None both when intj has no entry for this torch and when it has one the running
    torch disagrees with.  The disagreement matters as much as the absence: the
    offsets in the same entry were measured against *that* set of dtypes, and a
    torch that has since renamed, dropped or inserted one is a torch those
    offsets were never verified on.  Refusing sends the caller to `CPYTHON`,
    which assumes no layout at all.
    """
    recorded = _DTYPES.get(version or torch_version())
    if recorded is None or recorded != live_dtypes():
        return None
    return itemsize_bytes(recorded)


@functools.lru_cache(maxsize=1)
def dtype_index_table() -> bytes:
    """torch dtype code -> a 5-bit index over the dtypes triton accepts.

    The spec key encodes this rather than torch's raw `ScalarType` code so that
    the dtype, the divisibility bit and the pointer-range bit fit in one byte: at
    six bits the pointer codes alone fill all 256 and leave nowhere for the
    scalar tags.  Torch is already at 45 of its 64 codes and adds them faster
    than triton grows element types, so the compact space also has the headroom
    the raw one no longer does.

    Two torch dtypes share an index exactly when triton canonicalizes them to the
    same type -- `bool`, `uint1` and `int1` are all `u1` -- which keeps the key
    as fine as triton's specialization and no finer.  `0xFF` means "triton does
    not take this dtype", and is the bound check the C side raises on.

    Built from the live torch and the installed triton, never hardcoded: what a
    module keys on has to describe the pair that is running now.
    """
    import torch
    from triton._utils import type_canonicalisation_dict

    by_code: dict[int, Any] = {}
    for name in dir(torch):
        value = getattr(torch, name, None)
        if not isinstance(value, torch.dtype):
            continue
        code = dtype_code(value)
        if 0 <= code < NDTYPES:
            by_code[code] = value

    table = bytearray(b"\xff" * NDTYPES)
    indices: dict[str, int] = {}
    for code in sorted(by_code):  # code order, so the assignment is stable
        # `str(dtype)` is what triton's own canonicalize_dtype splits; the
        # attribute name is not.  `torch.chalf` and `torch.complex32` are one
        # dtype, and only the latter spelling is ever a key in that dict.
        canon = type_canonicalisation_dict.get(str(by_code[code]).split(".")[-1])
        if canon is None:
            continue
        table[code] = indices.setdefault(canon, len(indices))

    if len(indices) > 32:  # pragma: no cover - triton would have to double
        raise RuntimeError(
            f"intj: triton now has {len(indices)} element types, which no longer "
            "fit the spec key's 5-bit dtype index"
        )
    return bytes(table)


#: The verified torch ABIs, as a data file beside this module.
#:
#: Every number in it must be *measured*, never reasoned about: run
#: `python -m intj.torch_intf.abi_detect` on the target torch and paste what it
#: prints.  `test_hardcoded_layout_matches_this_torch` re-checks the entry for
#: whatever torch the suite runs against, with both detectors.
_ABI_PATH = pathlib.Path(__file__).with_name("torch_abi.toml")

#: `sizeof(PyObject)` on the builds every entry was measured on: default, GIL
#: builds.  `cdata` sits right past that header, so on a free-threaded build,
#: whose header is 32 bytes, the same offset reads the wrong field.  Such a build
#: gets no layout, and AUTO moves on to CXX or CPYTHON.
#: ponytail: free-threaded builds get no SHIM; key entries on the header size
#: too if that mode is wanted there.
MEASURED_PYOBJECT_SIZE = 16

#: Field names of `TensorABI` that an entry carries as offsets, in its order.
OFFSETS = tuple(f.name for f in dataclasses.fields(TensorABI) if f.name != "itemsize")


def _parse_abi(
    text: str,
) -> dict[tuple[int, int], tuple[dict[str, int], dict[int, tuple[str, int]]]]:
    """`["major.minor"]` tables of offsets plus a `dtypes` list indexed by code.

    The file is pasted by hand, so anything off-shape raises rather than being
    skipped: a skipped entry is a torch intj silently stops supporting, and a
    misread one is offsets it reads through.
    """

    def bad(why: str) -> ValueError:
        return ValueError(f"intj: torch_abi.toml {why}")

    try:
        doc = tomllib.loads(text)
    except tomllib.TOMLDecodeError as e:
        raise bad(f"does not parse: {e}") from None
    table: dict[tuple[int, int], tuple[dict[str, int], dict[int, tuple[str, int]]]] = {}
    for version, entry in doc.items():
        major, _, minor = version.partition(".")
        if not (major.isdigit() and minor.isdigit()):
            raise bad(f"has {version!r} where a major.minor version belongs")
        if not isinstance(entry, dict) or set(entry) != {*OFFSETS, "dtypes"}:
            raise bad(f"[{version!r}] must have exactly {', '.join(OFFSETS)} and dtypes")
        offsets: dict[str, Any] = {k: entry[k] for k in OFFSETS}
        # the C side keeps offsets in uint16_t; a larger one would wrap, not fail
        if not all(type(v) is int and 0 <= v < 1 << 16 for v in offsets.values()):
            raise bad(f"[{version!r}] has an offset that is not a 16-bit integer")
        dtypes: Any = entry["dtypes"]
        if not (
            isinstance(dtypes, list)
            and len(dtypes) <= NDTYPES
            and all(
                isinstance(d, list) and len(d) == 2
                and isinstance(d[0], str) and type(d[1]) is int and 0 < d[1] < 256
                for d in dtypes
            )
        ):
            raise bad(f"[{version!r}] dtypes must be at most {NDTYPES} [name, size] pairs")
        table[(int(major), int(minor))] = (
            offsets,
            {code: (name, size) for code, (name, size) in enumerate(dtypes)},
        )
    return table


_ABI = _parse_abi(_ABI_PATH.read_text())
_LAYOUTS = {v: offsets for v, (offsets, _) in _ABI.items()}
_DTYPES = {v: dtypes for v, (_, dtypes) in _ABI.items()}


def supported_versions() -> list[tuple[int, int]]:
    return sorted(_LAYOUTS)


@functools.lru_cache(maxsize=4)
def layout_for(version: tuple[int, int] | None = None) -> TensorABI | None:
    """The layout for `version`, or None if intj has no verified entry for it.

    None rather than a guess: a wrong offset cannot raise, it reads whatever
    happens to be at that address and hands the kernel a pointer built from it.
    An entry whose `dtypes` no longer describe the running torch counts as no
    entry at all -- see `itemsize_table` -- and so does every entry on a build
    whose `PyObject` header is not the one they were measured under.
    """
    if pyobject_size() != MEASURED_PYOBJECT_SIZE:
        return None
    version = version or torch_version()
    offsets = _LAYOUTS.get(version)
    items = itemsize_table(version)
    if offsets is None or items is None:
        return None
    return TensorABI(itemsize=items, **offsets)


@functools.lru_cache(maxsize=1)
def torch_version() -> tuple[int, int]:
    import torch

    major, _, rest = torch.__version__.partition(".")
    minor = rest.partition(".")[0]
    return (int(major), int(minor))
